# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfFileLogger
    param:
      level:   err
      loggers: ~
      file:    %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    param:
      delivery_strategy: none

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

#  storage:
#    class: sfNoStorage
#    class: sfMongoSessionStorage
#    param:
#      session_name: 5itv_sess
#      database: mondongo
#      db_table: session

  storage:
    class: sfNoStorage
    param:
      session_name: 5itv_sess
      database: mondongo
      db_table: session
      
  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host:       smtp.huan.tv
          port:       25
          encryption: ~
          username:   qianghaiming-ex@huan.tv
          password:   huanwanghuanwang